spring:
  application:
    name: guestbook-service
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://mysql:3306/app?autoReconnect=true
    username: root
    password: yourpassword
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      globally_quoted_identifiers: true
  sleuth:
    sampler:
      probability: 1.0
